### ISSUE TITLE
Storing enum as an int

### ISSUE THREAD

**Issue by tosh1100** [cjakoba/Bamazon#1]
Can you explain how the storing an int as an enum thing going to work? Won't the compiler get mad when we try to pass the int to the char *category_to_str(category c) method?

**Comment by cjakoba** [comment]
The compiler interprets enum values as integers. So essentially the integer 0, is the same thing as saying category 0 also known as "clothes". Since the enum is treated as an integer, I can use that to my advantage as an array indexer, and just make a local array filled with the same enum values, copy the selected value into malloced address, and return that address which will be string version of the enum. 

Unfortunately in C, there is no direct way of accessing the enum names (Clothes, tools, etc). You can only get out what they represent in integers. Which is why the category_to_str function is set up the way it is.
